fn main() {
    cc::Build::new()
        .cpp(true)
        .debug(true)
        .file("src/BufferDispenser.cpp")
        .file("src/real.cpp")
        .file("src/hwvertexbuffer.cpp")
        .file("src/dynarrayimpl.cpp")
        .file("src/hwrasterizer.cpp")
        .file("src/aarasterizer.cpp")
        .file("src/aacoverage.cpp")
        .file("src/bezier.cpp")
        .file("src/main.cpp")
        .flag("-Isrc")
        .flag("-std=gnu++11")
        .flag("-fdelayed-template-parsing")
        .flag("-fms-extensions")
        .flag("-Wno-unused-value")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-deprecated-register")
        .flag("-Wno-extra-tokens")
        .flag("-Wno-pragma-pack")
        .flag("-Wno-macro-redefined")
        .define("PAL_STDCPP_COMPAT", None)
        .define("FEATURE_PAL", None)
        .define("PLATFORM_UNIX", None)
        .define("_AMD64_", None)
        .define("_M_AMD64", None)
        .define("_M_X64", None)
        .compile("wpf_foo");
}
